    # This workflow will build a .NET project
    # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

    name: .NET

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build:

        runs-on: ubuntu-latest

        permissions:
          contents: read
          packages: write
          id-token: write
          
        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        
        - name: Restore dependencies
          run: dotnet restore
        
        - name: Build
          run: dotnet build --no-restore
        
        - name: Test
          run: dotnet test --no-build --verbosity normal
          
        - name: Test
          run: dotnet test --no-build --verbosity normal --configuration Release --logger "trx;LogFileName=test-results.trx" || true
          
        - name: Test Report
          uses: dorny/test-reporter@v1
          if: success() || failure()    # run this step even if previous step failed
          with:
            name: DotNet Tests            # Name of the check run which will be created
            path: "**/test-results.trx"    # Path to test results
            reporter: dotnet-trx        # Format of test results
            fail-on-error: true

        - name: Log into registry
          uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract Docker metadata
          id: meta
          uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
          with:
            images: ozairm/subsequence-image

        - name: Build and push Docker image
          id: build-and-push
          uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}